name: build firmware

on:
  push:
    paths-ignore: 
      - ".gitignore"
      - "LICENSE"
      - "README.md"
      - "README_zh.md"
  workflow_dispatch:

permissions:
  contents: write

env:
  PICO_SDK_FETCH_FROM_GIT: 1
  PICO_SDK_FETCH_FROM_GIT_TAG: 2.3.0
  PICO_SDK_FETCH_FROM_GIT_PATH: pico-sdk

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Prepare build environment
      uses: carlosperate/arm-none-eabi-gcc-action@v1
    
    - name: Fetch code
      uses: actions/checkout@v6
      with:
        submodules: recursive
        
    - name: Cache Pico SDK
      uses: actions/cache@v5
      with:
        path: pico-sdk
        key: pico-sdk-${{ env.PICO_SDK_FETCH_FROM_GIT_TAG }}

    - name: Build for Pico
      run: |
        cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=MinSizeRel -DPICO_BOARD=pico
        cmake --build build
        mv build/U2HTS.uf2 U2HTS_pico.uf2

    - name: Build for Pico2
      run: |
        cmake --fresh -B build -G Ninja -DCMAKE_BUILD_TYPE=MinSizeRel -DPICO_BOARD=pico2
        cmake --build build
        mv build/U2HTS.uf2 U2HTS_pico2.uf2

    - name: Build for Pico (FreeRTOS)
      run: |
        cmake --fresh -B build -G Ninja -DCMAKE_BUILD_TYPE=MinSizeRel -DPICO_BOARD=pico -DU2HTS_ENABLE_FREERTOS=ON
        cmake --build build
        mv build/U2HTS.uf2 U2HTS_pico_freertos.uf2

    - name: Build for Pico2 (FreeRTOS)
      run: |
        cmake --fresh -B build -G Ninja -DCMAKE_BUILD_TYPE=MinSizeRel -DPICO_BOARD=pico2 -DU2HTS_ENABLE_FREERTOS=ON
        cmake --build build
        mv build/U2HTS.uf2 U2HTS_pico2_freertos.uf2

    - name: Upload firmware
      uses: actions/upload-artifact@v7
      with:
        name: ${{ github.event.repository.name }}_RP2-${{ github.run_id }}
        path: |
          U2HTS_pico.uf2
          U2HTS_pico2.uf2
          U2HTS_pico_freertos.uf2
          U2HTS_pico2_freertos.uf2
          
    - name: Publish release
      uses: softprops/action-gh-release@v3
      if: github.ref_type == 'tag'
      with:
        files: |
          U2HTS_pico.uf2
          U2HTS_pico2.uf2
          U2HTS_pico_freertos.uf2
          U2HTS_pico2_freertos.uf2
